### ISSUE TITLE
Error reading selected elements (n, o, p, s) inside brackets

### ISSUE THREAD

**Issue by retsoko** [metamolecular/balsa#1]
Reading any string that contains selected elements (except C) inside brackets fails.
Some examples and their respective errors during parsing:
- [nH]1cccc1 (Error: Character(1))
- [18o]1cccc1 (Error: Character(3))
- [pH]1cccc1 (Error: Character(1))
- [36s]1cccc1 (Error: Character(3))

By the production rules in the [Balsa specification](https://github.com/metamolecular/balsadoc) all the above should be correct, nevertheless they all fail to be parsed.

```
<bracket> ::= "[" <isotope>? <symbol> <parity>? <virtual_hydrogen>? <charge>? "]"  
<symbol> ::= <star> | <element> | <selection>  
<selection> ::= "c" | "n" | "o" | "p" | "s"  
```

**Comment by rapodaca** [comment]
Thanks for catching and fixing this.
